databases:
  - name: lifelinkdb
    plan: free
    databaseName: lifelink
    user: lifelink

services:
  - type: web
    name: lifelink
    plan: free  # <--- This is the crucial addition!
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn lifelink.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lifelinkdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4