# Generated by Django 6.0.7 on 2026-07-08 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='hospital_details',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='required_date',
        ),
        migrations.RemoveField(
            model_name='organpledge',
            name='pledge_date',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_name',
            field=models.CharField(default='Default Hospital', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='units_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organpledge',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='organpledge',
            name='organ_name',
            field=models.CharField(choices=[('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Heart', 'Heart'), ('Cornea', 'Cornea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qr_code',
            field=models.ImageField(blank=True, default='', upload_to='qr_codes/'),
            preserve_default=False,
        ),
    ]
