# Generated by Django 6.0.7 on 2026-07-08 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_bloodrequest_hospital_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(choices=[('City Medical Center', 'City Medical Center'), ('Central Health Hospital', 'Central Health Hospital'), ('National Care Institute', 'National Care Institute'), ('Riverbank General Hospital', 'Riverbank General Hospital'), ('Pioneer Trauma Center', 'Pioneer Trauma Center')], max_length=100)),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00 AM - 12:00 PM', '09:00 AM - 12:00 PM'), ('12:00 PM - 03:00 PM', '12:00 PM - 03:00 PM'), ('03:00 PM - 06:00 PM', '03:00 PM - 06:00 PM')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
