# Generated by Django 6.0.7 on 2026-07-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donationslot_hospitalappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organ_pledge',
            field=models.CharField(choices=[('None', 'None'), ('Kidneys', 'Kidneys'), ('Liver', 'Liver'), ('Cornea', 'Cornea'), ('Heart', 'Heart'), ('Lungs', 'Lungs'), ('Pancreas', 'Pancreas')], default='None', max_length=50),
        ),
    ]
