# Generated by Django 6.0.7 on 2026-07-08 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_organ_pledge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('camp_date', models.DateField()),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='units_required',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='priority',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Normal', 'Normal')], default='Normal', max_length=10),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='donor_id',
            field=models.CharField(blank=True, null=True, max_length=32, unique=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='life_saving_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organ_pledge',
            field=models.CharField(choices=[('None', 'None'), ('Heart', 'Heart'), ('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Lungs', 'Lungs'), ('Eyes', 'Eyes'), ('Pancreas', 'Pancreas')], default='None', max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_needed', models.CharField(choices=[('None', 'None'), ('Heart', 'Heart'), ('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Lungs', 'Lungs'), ('Eyes', 'Eyes'), ('Pancreas', 'Pancreas')], max_length=50)),
                ('hospital_name', models.CharField(max_length=200)),
                ('verification_status', models.CharField(choices=[('Hospital Verification Pending', 'Hospital Verification Pending'), ('Verified', 'Verified')], default='Hospital Verification Pending', max_length=80)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
