# Generated by Django 6.0.7 on 2026-07-08 07:02

from django.db import migrations, models
import uuid


def populate_donor_ids(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    for profile in UserProfile.objects.all():
        if not profile.donor_id:
            profile.donor_id = f"LL-{uuid.uuid4().hex[:10].upper()}"
            profile.save(update_fields=['donor_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_donationcamp_remove_bloodrequest_donor_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_donor_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='donor_id',
            field=models.CharField(blank=True, null=True, max_length=32, unique=True),
        ),
    ]
